name: Moralis launch
on: [push]
jobs:
  Moralis-Launch:
    runs-on: ubuntu-latest
    env:
      working-directory: ./ruilwinkel
    steps:
      - run: sh npm install
      - run: echo  "completed switch to ruilwinkel directory"
